CREATE TABLE IF NOT EXISTS raw.ft_balance_f (
    ON_DATE TEXT,
    ACCOUNT_RK TEXT,
    CURRENCY_RK TEXT,
    BALANCE_OUT TEXT
);

CREATE TABLE IF NOT EXISTS raw.ft_posting_f (
    OPER_DATE TEXT,
    CREDIT_ACCOUNT_RK TEXT,
    DEBET_ACCOUNT_RK TEXT,
    CREDIT_AMOUNT TEXT,
    DEBET_AMOUNT TEXT
);

CREATE TABLE IF NOT EXISTS raw.md_account_d (
    DATA_ACTUAL_DATE TEXT,
    DATA_ACTUAL_END_DATE TEXT,
    ACCOUNT_RK TEXT,
    ACCOUNT_NUMBER TEXT,
    CHAR_TYPE TEXT,
    CURRENCY_RK TEXT,
    CURRENCY_CODE TEXT
);

CREATE TABLE IF NOT EXISTS raw.md_currency_d (
    CURRENCY_RK TEXT,
    DATA_ACTUAL_DATE TEXT,
    DATA_ACTUAL_END_DATE TEXT,
    CURRENCY_CODE TEXT,
    CODE_ISO_CHAR TEXT
);

CREATE TABLE IF NOT EXISTS raw.md_exchange_rate_d (
    DATA_ACTUAL_DATE TEXT,
    DATA_ACTUAL_END_DATE TEXT,
    CURRENCY_RK TEXT,
    REDUCED_COURCE TEXT,
    CODE_ISO_NUM TEXT
);

CREATE TABLE IF NOT EXISTS raw.md_ledger_account_s (
    CHAPTER TEXT,
    CHAPTER_NAME TEXT,
    SECTION_NUMBER TEXT,
    SECTION_NAME TEXT,
    SUBSECTION_NAME TEXT,
    LEDGER1_ACCOUNT TEXT,
    LEDGER1_ACCOUNT_NAME TEXT,
    LEDGER_ACCOUNT TEXT,
    LEDGER_ACCOUNT_NAME TEXT,
    CHARACTERISTIC TEXT,
    START_DATE TEXT,
    END_DATE TEXT
    );